<a href="https://colab.research.google.com/github/sriram200386-lgtm/Python-DA-Assignment-1-Data-Analysis-using-NumPy-and-Pandas/blob/main/Python_DA_Assignment_1%E2%80%94Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Series

In [ ]:
import pandas as pd
marks=[95,92,89,85,80]
se=pd.Series(marks,index=['Rank1','Rank2','Rank3','Rank4','Rank5'])
se

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
se[0]

/tmp/ipykernel_2164/1614452337.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  se[0]

np.int64(95)

In [ ]:
se.loc['Rank1':'Rank3']

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [ ]:
se.iloc[2]

np.int64(89)

In [ ]:
se[se>90]

Rank1    95
Rank2    92
dtype: int64

In [ ]:
se.loc['Rank1']=100
se

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
se.drop('Rank5')

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
cgp=se/10
cgp

Rank1                                                 10.0
Rank2                                                  9.2
Rank3                                                  8.9
Rank4                                                  8.5
Rank5                                                  8.0
CGP      Rank1                                         ...
dtype: object

##Data Frame

In [ ]:
import pandas as pd

data={'TransactionID':[ 101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
      'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
      'Region':[ 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'],
      'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
    }
df=pd.DataFrame(data)
df

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
df.head(2)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150

In [ ]:
df.tail(2)

   TransactionID ProductCategory Region  Amount
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
df.shape

(10, 4)

In [ ]:
df.size

40

In [ ]:
df.values

array([[101, 'Electronics', 'North', 200],
       [102, 'Clothing', 'South', 150],
       [103, 'Electronics', 'North', 300],
       [104, 'Furniture', 'East', 450],
       [105, 'Clothing', 'West', 200],
       [106, 'Electronics', 'North', 250],
       [107, 'Furniture', 'East', 300],
       [108, 'Clothing', 'West', 180],
       [109, 'Furniture', 'South', 350],
       [110, 'Electronics', 'North', 400]], dtype=object)

In [ ]:
df.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
df[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
df.iloc[-3:]

   TransactionID ProductCategory Region  Amount
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
#df['Region']=='North'
df[(df['Region']=='North') & (df['Amount']>200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
df.value_counts('ProductCategory')

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
df['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
avg=df.groupby('Region')['Amount'].mean()
avg

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
df.loc[df['TransactionID']==102,'Amount']=165
df

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
df['Discount']=df['Amount']*0.10
df

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
df.drop(8,axis=0)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
df.drop('Discount',axis=1)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400